### ISSUE TITLE
Behavior of "Toggle Media Mute"

### ISSUE THREAD

**Issue by VourMa** [zacharee/nobar-issues#107]
The "Toggle Media Mute" gesture mutes the media successfully with the first activation. (Very useful addition btw, thank you!)
If one performs the same gesture for a second time (without manually adjusting the volume in between), the volume skyrockets to maximum. I think that the second same gesture should return the volume to the previous (non-zero) level it was before the first gesture was performed, just like the media button in the volume menu on Android Pie does.

An example to make myself more clear:
Volume level = 60% --> "Toggle Media Mute" gesture ==>
Volume level = 0% --> "Toggle Media Mute" gesture ==>
Volume level = 60% (instead of 100%, that it is now)

**Comment by zacharee** [comment]
It’s using the built-in behavior of Android right now. It doesn’t work to unmute at all on Samsung. I’ll look into replicating the proper behavior.

Sent from Mail for Windows 10

From: Manos Vourliotis
Sent: Thursday, May 16, 2019 11:49 AM
To: zacharee/nobar-issues
Cc: Subscribed
Subject: [zacharee/nobar-issues] Behavior of "Toggle Media Mute" (#107)

The "Toggle Media Mute" gesture mutes the media successfully with the first activation. (Very useful addition btw, thank you!)
If one performs the same gesture for a second time (without manually adjusting the volume in between), the volume skyrockets to maximum. I think that the second same gesture should return the volume to the previous (non-zero) level it was before the first gesture was performed, just like the media button in the volume menu on Android Pie does.
An example to make myself more clear:
Volume level = 60% --> "Toggle Media Mute" gesture ==>
Volume level = 0% --> "Toggle Media Mute" gesture ==>
Volume level = 60% (instead of 100%, that it is now)

**Comment by VourMa** [comment]
Ok, I see. Thank you!

**Comment by zacharee** [comment]
https://github.com/zacharee/nobar-issues/releases/tag/1.12.2
