### ISSUE TITLE
Screen lock

### ISSUE THREAD

**Issue by Keviiiii** [zacharee/nobar-issues#119]
Currently; The "Lock screen" & "Screen timeout" functions both does same function, which is completely dim the brightness & after 10 seconds it gets locked. (on Miui redmi 5)

**How should this behavior be changed?**
It will be better if "screen lock" option instantly locked the screen by utilizing "device administrator". Asking for this permission only when screen lock option enabled will be better. 
**Additional context**

**Comment by zacharee** [comment]
We've decided against implementing a Device Administrator for the time being. It's not a great option for locking the screen, since it prevents biometric unlock from working.

As for the "Toggle Screen Timeout" action, that doesn't set the screen timeout. It uses an overlay that prevents the device from sleeping.
